In [1]:
from importlib import reload
import sys
from imp import reload
import warnings
warnings.filterwarnings('ignore')
if sys.version[0] == '2':
    reload(sys)
    sys.setdefaultencoding("utf-8")

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('./imdb_master.csv',encoding="latin-1")
df.head()

Unnamed: 0  type                                             review label  \
0           0  test  Once again Mr. Costner has dragged out a movie...   neg   
1           1  test  This is an example of why the majority of acti...   neg   
2           2  test  First of all I hate those moronic rappers, who...   neg   
3           3  test  Not even the Beatles could write songs everyon...   neg   
4           4  test  Brass pictures (movies is not a fitting word f...   neg   

          file  
0      0_2.txt  
1  10000_4.txt  
2  10001_1.txt  
3  10002_3.txt  
4  10003_3.txt

In [4]:
df = df.drop(['Unnamed: 0','type','file'],axis=1)
df.columns = ["review","sentiment"]
df.head()

review sentiment
0  Once again Mr. Costner has dragged out a movie...       neg
1  This is an example of why the majority of acti...       neg
2  First of all I hate those moronic rappers, who...       neg
3  Not even the Beatles could write songs everyon...       neg
4  Brass pictures (movies is not a fitting word f...       neg

In [5]:
df = df[df.sentiment != 'unsup']
df['sentiment'] = df['sentiment'].map({'pos': 1, 'neg': 0})
df.head()

review  sentiment
0  Once again Mr. Costner has dragged out a movie...          0
1  This is an example of why the majority of acti...          0
2  First of all I hate those moronic rappers, who...          0
3  Not even the Beatles could write songs everyon...          0
4  Brass pictures (movies is not a fitting word f...          0

In [6]:
neg = 0
pos = 0
for i in range(len(df)):
    if df['sentiment'][i] == 0:
        neg += 1
    elif df['sentiment'][i] == 1:
        pos += 1
        
print(neg)
print(pos)

25000
25000


In [7]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/jiayang/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/jiayang/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [8]:
import re
from nltk import*
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
stop_words = set(stopwords.words("english")) 
lemmatizer = WordNetLemmatizer()

tokenizer = RegexpTokenizer(r'\w+')
df['Processed_Reviews'] = df['review'].apply(lambda x: tokenizer.tokenize(x.lower())) 

df.head()

review  sentiment  \
0  Once again Mr. Costner has dragged out a movie...          0   
1  This is an example of why the majority of acti...          0   
2  First of all I hate those moronic rappers, who...          0   
3  Not even the Beatles could write songs everyon...          0   
4  Brass pictures (movies is not a fitting word f...          0   

                                   Processed_Reviews  
0  [once, again, mr, costner, has, dragged, out, ...  
1  [this, is, an, example, of, why, the, majority...  
2  [first, of, all, i, hate, those, moronic, rapp...  
3  [not, even, the, beatles, could, write, songs,...  
4  [brass, pictures, movies, is, not, a, fitting,...

In [9]:
# def remove_stopwords(text):
#     words = [w for w in text if w not in stopwords.words('english')]
#     print('1')
#     return words
# df['Processed_Reviews'] = df['Processed_Reviews'].apply(lambda x:[w for w in x if w not in stopwords.words('english')])
stop_words = set(stopwords.words('english'))
df['Processed_Reviews'] = df['Processed_Reviews'].apply(lambda x: [word for word in x if word not in stop_words])
df.head()

review  sentiment  \
0  Once again Mr. Costner has dragged out a movie...          0   
1  This is an example of why the majority of acti...          0   
2  First of all I hate those moronic rappers, who...          0   
3  Not even the Beatles could write songs everyon...          0   
4  Brass pictures (movies is not a fitting word f...          0   

                                   Processed_Reviews  
0  [mr, costner, dragged, movie, far, longer, nec...  
1  [example, majority, action, films, generic, bo...  
2  [first, hate, moronic, rappers, could, nt, act...  
3  [even, beatles, could, write, songs, everyone,...  
4  [brass, pictures, movies, fitting, word, reall...

In [10]:
lemmatizer = WordNetLemmatizer()

def word_lemmatizer(text):
    lem_text = [lemmatizer.lemmatize(i) for i in text]
    return lem_text
df['Processed_Reviews'] = df['Processed_Reviews'].apply(lambda x :word_lemmatizer(x))
df.head()

review  sentiment  \
0  Once again Mr. Costner has dragged out a movie...          0   
1  This is an example of why the majority of acti...          0   
2  First of all I hate those moronic rappers, who...          0   
3  Not even the Beatles could write songs everyon...          0   
4  Brass pictures (movies is not a fitting word f...          0   

                                   Processed_Reviews  
0  [mr, costner, dragged, movie, far, longer, nec...  
1  [example, majority, action, film, generic, bor...  
2  [first, hate, moronic, rapper, could, nt, act,...  
3  [even, beatles, could, write, song, everyone, ...  
4  [brass, picture, movie, fitting, word, really,...

In [11]:
def list_to_str(alist):
    a = " ".join(alist)
    return a
df['str_Reviews'] = df['Processed_Reviews'].apply(lambda x :list_to_str(x))
df.head()

review  sentiment  \
0  Once again Mr. Costner has dragged out a movie...          0   
1  This is an example of why the majority of acti...          0   
2  First of all I hate those moronic rappers, who...          0   
3  Not even the Beatles could write songs everyon...          0   
4  Brass pictures (movies is not a fitting word f...          0   

                                   Processed_Reviews  \
0  [mr, costner, dragged, movie, far, longer, nec...   
1  [example, majority, action, film, generic, bor...   
2  [first, hate, moronic, rapper, could, nt, act,...   
3  [even, beatles, could, write, song, everyone, ...   
4  [brass, picture, movie, fitting, word, really,...   

                                         str_Reviews  
0  mr costner dragged movie far longer necessary ...  
1  example majority action film generic boring re...  
2  first hate moronic rapper could nt act gun pre...  
3  even beatles could write song everyone liked a...  
4  brass picture movie fitting word really somewh...

In [12]:
df = df.drop(['review'], axis=1)
df.head()

sentiment                                  Processed_Reviews  \
0          0  [mr, costner, dragged, movie, far, longer, nec...   
1          0  [example, majority, action, film, generic, bor...   
2          0  [first, hate, moronic, rapper, could, nt, act,...   
3          0  [even, beatles, could, write, song, everyone, ...   
4          0  [brass, picture, movie, fitting, word, really,...   

                                         str_Reviews  
0  mr costner dragged movie far longer necessary ...  
1  example majority action film generic boring re...  
2  first hate moronic rapper could nt act gun pre...  
3  even beatles could write song everyone liked a...  
4  brass picture movie fitting word really somewh...

In [15]:
import json
data = json.load(open('processed_data.json', 'r'))
print(data)
list_sen = [2 for i in range(len(data))]
df2 = pd.DataFrame(data={"Processed_Reviews": data, "sentiment": list_sen})
df2['str_Reviews'] = df2['Processed_Reviews'].apply(lambda x :list_to_str(x))

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [16]:
df = pd.concat([df, df2]).reset_index(drop=True)
df.head()

Processed_Reviews  sentiment  \
0  [mr, costner, dragged, movie, far, longer, nec...          0   
1  [example, majority, action, film, generic, bor...          0   
2  [first, hate, moronic, rapper, could, nt, act,...          0   
3  [even, beatles, could, write, song, everyone, ...          0   
4  [brass, picture, movie, fitting, word, really,...          0   

                                         str_Reviews  
0  mr costner dragged movie far longer necessary ...  
1  example majority action film generic boring re...  
2  first hate moronic rapper could nt act gun pre...  
3  even beatles could write song everyone liked a...  
4  brass picture movie fitting word really somewh...

In [17]:
df.tail()

Processed_Reviews  sentiment  \
95241  [holey, captain, crud, mine, say, copy, window...          2   
95242  [tablet, month, the, bad, thing, touchscreen, ...          2   
95243       [addons, chrome, touch, mozilla, grab, drag]          2   
95244                             [it, hard, drive, ssd]          2   
95245  [hold, galaxy, tab, 10.1, know, weak, creaky, ...          2   

                                             str_Reviews  
95241  holey captain crud mine say copy window genuin...  
95242  tablet month the bad thing touchscreen mine ma...  
95243              addons chrome touch mozilla grab drag  
95244                                  it hard drive ssd  
95245         hold galaxy tab 10.1 know weak creaky mean

In [18]:
all_words = []
for i in df['Processed_Reviews']:
#     print(len(df['Processed_Reviews'][i])
    for j in i:
        all_words.append(j)
print(len(all_words))
vocab = set(all_words)  
len_vocab = len(vocab)
print(len_vocab)

6643545
110387


In [28]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Dense , Input , LSTM , Embedding, Dropout , Activation, GRU, Flatten
from keras.layers import Bidirectional, GlobalMaxPool1D
from keras.models import Model, Sequential
from keras.layers import Convolution1D
from keras import initializers, regularizers, constraints, optimizers, layers
from sklearn.model_selection import train_test_split
max_features = len_vocab
tokenizer = Tokenizer(num_words=max_features)
tokenizer.fit_on_texts(df['str_Reviews'])
list_tokenized = tokenizer.texts_to_sequences(df['str_Reviews'])
print(type(list_tokenized))
print(list_tokenized[0])
print(df['str_Reviews'][0])
maxlen = 130
X = pad_sequences(list_tokenized, maxlen=maxlen, padding='post')[:50000]
y = df['sentiment'][:50000]

X_pre = pad_sequences(list_tokenized, maxlen=maxlen, padding='post')[50000:]
y_pre = df['sentiment'][50000:]

<class 'list'>
[286, 6855, 3357, 2, 123, 1029, 1649, 1069, 1273, 1424, 1874, 320, 273, 9, 80, 960, 3686, 6855, 9, 1633, 309, 1463, 18, 218, 7, 273, 9, 15, 273, 9180, 31586, 9492, 8921, 186, 49, 131, 27, 55, 145, 226, 91, 25, 1277, 16380, 3686, 5977, 653, 1664, 6855, 313, 16, 412, 213, 23, 82, 3413, 6855, 153, 80, 8921, 960, 481, 8921, 1932, 38, 2476, 14229, 10790, 1259, 29, 180, 1558, 209]
mr costner dragged movie far longer necessary aside terrific sea rescue sequence care character u ghost closet costner character realized early forgotten much later time care character really care cocky overconfident ashton kutcher problem come kid think better anyone else around show sign cluttered closet obstacle appears winning costner finally well past half way point stinker costner tell u kutcher ghost told kutcher driven best prior inkling foreshadowing magic could keep turning hour


In [29]:
print(list_tokenized[95241])
print(df['str_Reviews'][95241])

[37938, 1436, 13334, 986, 36, 646, 1116, 1870, 27, 1416, 56, 704, 38638, 47942, 633, 133, 657, 405, 40725, 9389, 107442, 133, 7192, 25362, 57, 7192, 107443]
holey captain crud mine say copy window genuine think do something ... plus geting replacment touch screen fit soon aparently archos outsources screen repair upto find repair depo ...


In [30]:

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.05,
    shuffle=True,
    random_state=42)
print(len(X_train))
print(len(X_test))
print(type(y_train))
print(X_test)

47500
2500
<class 'pandas.core.series.Series'>
[[  689    88  3418 ...     0     0     0]
 [  184  4728  7621 ...  3216   812    18]
 [   63 20219 48408 ...     0     0     0]
 ...
 [   65    25   630 ...   129     7    35]
 [ 2269   667 26892 ...  3627   560    75]
 [  349     2   366 ...     0     0     0]]


In [31]:
print(y_test)

33553    0
9427     0
199      0
12447    0
39489    1
42724    1
10822    0
49498    1
4144     0
36958    0
43106    1
38695    1
6188     0
1414     0
18471    1
29282    0
15177    1
34304    0
12609    1
12144    0
6113     0
15908    1
821      0
15118    1
13466    1
26497    0
42111    1
30188    0
37237    0
33109    0
        ..
926      0
35817    0
10115    0
8318     0
26072    0
29729    0
9625     0
3785     0
20885    1
6904     0
6478     0
27148    0
33657    0
38899    1
26816    0
35546    0
41571    1
24447    1
30245    0
22557    1
45578    1
17735    1
25980    0
5864     0
6529     0
10536    0
28212    0
7360     0
38902    1
12510    1
Name: sentiment, Length: 2500, dtype: int64


In [33]:

embed_size = 256
model = Sequential()
model.add(Embedding(max_features, embed_size))
model.add(Bidirectional(LSTM(32, return_sequences = True)))
model.add(GlobalMaxPool1D())
model.add(Dense(20, activation="relu"))
model.add(Dropout(0.3))
model.add(Dense(1, activation="sigmoid"))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

batch_size = 100
epochs = 1
model.fit(X_train,y_train, validation_data=(X_test, y_test),batch_size=batch_size, epochs=epochs)

Train on 47500 samples, validate on 2500 samples
Epoch 1/1
47500/47500 [==============================] - 375s 8ms/step - loss: 0.3465 - acc: 0.8532 - val_loss: 0.2566 - val_acc: 0.8952


In [34]:
Y_pred = model.predict_classes(X_pre)

45246/45246 [==============================] - 197s 4ms/step


In [38]:
print(Y_pred)
print(type(Y_pred))
print(type(Y_pred[0]))

[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [0]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [39]:
Y_pred = Y_pred.tolist()

json.dump(Y_pred, open('predict.json', 'w'))  

In [40]:
model.save('my_model.h5')